spring.application.name=UAM-LIFT
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/UamLift2
spring.datasource.username=postgres
spring.datasource.password=fernando



spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Email verification
app.email.verification.ttl-minutes=10

# SMTP (ajusta segun tu proveedor)
spring.mail.host=fergomez@uamv.edu.ni
spring.mail.port=587
spring.mail.username=fergomez@uamv.edu.ni
spring.mail.password=ejemplopassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
