spring.application.name=UAM-LIFT
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/UamLift
spring.datasource.username=postgres
spring.datasource.password=1234



spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Email verification
app.email.verification.ttl-minutes=3 

# SMTP Configuración (Google Workspace / Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fergomez@uamv.edu.ni
# OJO: No pongas tu contraseña de la U, pon una Contraseña de Aplicación
spring.mail.password=aqui_va_tu_contraseña_de_aplicacion
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true