server.port=${PORT:8080}

# Conexión Segura de Supabase utilizando el Shared Pooler
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuración Hibernate
spring.jpa.hibernate.ddl-auto=update